# SPDX-FileCopyrightText: 2025 Severen Redwood <sev@severen.dev>
# SPDX-License-Identifier: CC0-1.0

name: Spelling

permissions:
  contents: read

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  spelling:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check spelling with typos
      uses: crate-ci/typos@master
